### ISSUE TITLE
Failing in create()...

### ISSUE THREAD

**Issue by hodonsky** [SamVerschueren/gulp-cordova-build-android#1]
Having a bit of an issue with the following:

``` js
// config.build == ~/app/build/ (however it's the full path, this just gives you an idea of app depth
// join = require( "path" ).join;
gulp.task( "build:package:cordova:android", function () {
  return gulp.src( config.build )
    .pipe( create( {
      dir: 'build',
      id: "com.appname.www",
      name: "AppName"
    } ) )
    .pipe( plugin( "org.apache.cordova.console" ) )
    .pipe( plugin( "org.apache.cordova.device" ) )
    .pipe( plugin( "org.apache.cordova.network-information" ) )
    .pipe( plugin( "org.apache.cordova.dialogs" ) )
    .pipe( plugin( "org.apache.cordova.file" ) )
    .pipe( android() )
    .pipe( gulp.dest( join( config.build, 'apk' ) ) );
});
```

gets to the gulp task with that bit in it, and just fails silently.
I'm using:

```
node@0.12.2
gulp@3.8.11
gulp-cordova-create@1.0.1
gulp-cordova-plugin@1.0.0
gulp-cordova-build-android@1.1.0
```

I get:

```
Starting 'build:package:cordova:android'...
~/: 
```

Have any ideas, or need more information?

**Comment by hodonsky** [comment]
Solved... apparently you have to put in some valid something to: `.pipe( create( {  } ) )`;

**Comment by hodonsky** [comment]
Nope... now it's failing silently for a different reason... Issue updated

**Comment by SamVerschueren** [comment]
I will have a look at it tomorrow

**Comment by hodonsky** [comment]
+1

**Comment by hodonsky** [comment]
Okay so it's failing silently because it was failing in the `create()` still and the error didn't output because it was being piped. Maybe this module doesn't handle forwarding of a failure down the pipe...? If I comment out everything but the first step it errors appropriately to the console.

**Comment by SamVerschueren** [comment]
Thanks for the extra info. Should have called everything v0.0.x because it's still quite in beta.

Have you tried passing no options at all? Just `create()` should create a `.cordova` directory.

What is `config.build` in your example?

**Comment by hodonsky** [comment]
well first time it did exactly that, I just didn't see it... however, I'm getting creative with my build...

first line of the issue. it's a little diluted because it's in docker but it's full path looks like: `/usr/src/app/app/build`

When actually the path string it's getting looks like this `/usr/src/app/.gulp/../app/build` (incase the `..` is messing with things)

**Comment by relicmelex** [comment]
well first time it did exactly that, I just didn't see it... however, I'm getting creative with my build...

**Comment by hodonsky** [comment]
Ugh. now I'm getting this:

```
/usr/src/utilities/node_modules/gulp-cordova-create/index.js:41
            config = {lib: {www: {url: firstFile.path}}};
```

**Comment by relicmelex** [comment]
Okay, so I think you should close this, and forward the issue over to cordova-create because that's where it looks like I'm actually having the issues. Not sure how to do that. Thanks for the support btw.

**Comment by hodonsky** [comment]
got it working... just strangely opinionated in how it takes options.

**Comment by SamVerschueren** [comment]
Can you explain how you fixed it? Always open to feedback.

**Comment by SamVerschueren** [comment]
This is what I tried

``` JavaScript
'use strict';

var gulp = require('gulp'),
    create = require('gulp-cordova-create'),
    plugin = require('gulp-cordova-plugin'),
    android = require('gulp-cordova-build-android'),
    join = require('path').join;

gulp.task('build', function() {
    return gulp.src('./dist')
        .pipe(create({
            dir: 'build',
            id: 'com.appname.www',
            name: 'AppName'
        }))
        .pipe(plugin( "org.apache.cordova.console"))
        .pipe(plugin( "org.apache.cordova.device"))
        .pipe(plugin( "org.apache.cordova.network-information" ))
        .pipe(plugin( "org.apache.cordova.dialogs"))
        .pipe(plugin( "org.apache.cordova.file"))
        .pipe(android())
        .pipe(gulp.dest(join('releases', 'apk')));
});
```

And it works fine. Maybe it's because you run it in a Docker container and some paths may not be correct?

**Comment by SamVerschueren** [comment]
In the meantime I found out that if you don't pipe it to `gulp.dest`, it will show you the errors. Otherwise it will not show the errors and kills the task silently.

I will close this issue. You can reopen it if you want to add more information or discuss things further.
