### ISSUE TITLE
Cordova-plugin-whitelist support

### ISSUE THREAD

**Issue by RDalziel** [SamVerschueren/gulp-cordova-build-android#11]
Do any of the tools in this area support the whitelist plugin?

I'd like to insert this tag into my config.xml

<allow-navigation href="http://*/*" />

How is this done with these gulp packages? Is this supported yet?

I'm getting 404 errors on any http requests from the generated package at the moment.

**Comment by SamVerschueren** [comment]
Hi @RDalziel 

This is semi-supported. The nework whitelisting is done via access origin tags which can be added with [gulp-cordova-access](https://github.com/samverschueren/gulp-cordova-access). Other tags are not supported via a specific plugin but can be added via [gulp-cordova-xml](https://github.com/samverschueren/gulp-cordova-xml).

But this is not the only thing you should do. Make sure you add the [content-security-policy](https://github.com/apache/cordova-plugin-whitelist#content-security-policy) tags in the head of your `index.html` file.

**Comment by RDalziel** [comment]
Ace Sam, thanks again for your help!

**Comment by SamVerschueren** [comment]
No problem ;)
