### ISSUE TITLE
Plugin cannot be run on a CI env

### ISSUE THREAD

**Issue by sbatezat** [SamVerschueren/gulp-cordova-build-android#13]
Hi Sam,

I'm prompt for my keystore's password using the plugin - but what about building of apps in a continuous integration env? I guess you should add an option to use password on the gulp file and so let CI env use your plugin. What your thoughts about that?

**Comment by SamVerschueren** [comment]
Hi @sbatezat 

It is possible to provide the passwords in the options object. Have a look at the api options object for `storePassword` and `keyPassword`. https://github.com/SamVerschueren/gulp-cordova-build-android#androidoptions

Let me know if this fits your needs.

**Comment by sbatezat** [comment]
My bad! Indeed everything is working fine with these parameters - sorry

**Comment by SamVerschueren** [comment]
No problem ;)
