### ISSUE TITLE
where search plugin keys?

### ISSUE THREAD

**Issue by WuglyakBolgoink** [SamVerschueren/gulp-cordova-build-android#20]
Hi,

if I use this path
        .pipe(android({storeFile: '/Path/to/key.keystore', keyAlias: 'my_alias'}))

keystore-file must be in folder "x:/../project/cordova/PATH/TO/KEYSTORE"
I start plugin with my gulp-task
My Project structure:

```
PROJECT/
--gulpfile.js
--
--build/
----cordova/
--
--src/
----js/
----blablabla/
----androidkeys/
```

in this case it doesn't work...
`.pipe(android({storeFile: 'src/androidkexs/key.keystore', keyAlias: 'my_alias'}))`
to fix this I write so 
`.pipe(android({storeFile: '../../../../src/androidkexs/key.keystore', keyAlias: 'my_alias'}))`

**Comment by SamVerschueren** [comment]
The description of the `storeFile` property says

> Absolute path to your key file.

The reason for that is that is writing a `release-signing.properties` file which refers to that file. That properties file is stored in your android project. So the easiest way of doing that is by providing an aboslute path.

``` js
.pipe(android({storeFile: path.join(__dirname, 'src/androidkexs/key.keystore'), keyAlias: 'my_alias'}))
```
