### ISSUE TITLE
Release apk

### ISSUE THREAD

**Issue by tonyneel923** [SamVerschueren/gulp-cordova-build-android#28]
I am using this library with the flag release: true in my options object but I build debug and unaligned debug regardless of the value of the flag. Any ideas on why this may be?

**Comment by SamVerschueren** [comment]
Have hou tried to sign the apk? https://github.com/SamVerschueren/gulp-cordova-build-android#sign-the-apk

**Comment by tonyneel923** [comment]
I have not tried to sign it. Is it not possible to create an u signed release apk? I would like to sign it separately. If not I will check that out.

**Comment by tonyneel923** [comment]
I was using an outdate version on a legacy project. My apologies.

**Comment by rebeccamcdougal** [comment]
I'm seeing a similar issue with version 3.0.0 and cordova-android 9.0.0. I have the release flag set to true and include a storeFile and keyAlias but it will only build a debug apk.
