### ISSUE TITLE
Doesn't copy the release apk to the `dest` folder

### ISSUE THREAD

**Issue by adonespitogo** [SamVerschueren/gulp-cordova-build-android#4]
Hi,

Thanks for this great tool. I just started using ionic and I add [crosswalk browser](http://ionicframework.com/docs/cli/browsers.html) to my application. Now when I build the project, the relase apk is not copied to the `dest` folder. I found out that the new release apk name after build has changed to these:

```
BUILD SUCCESSFUL

Total time: 12.638 secs
Built the following apk(s):
    /home/adones/Projects/Phonegap/PNPAA-Ionic/mobile/platforms/android/build/outputs/apk/android-x86-release.apk
    /home/adones/Projects/Phonegap/PNPAA-Ionic/mobile/platforms/android/build/outputs/apk/android-armv7-release.apk
    /home/adones/Projects/Phonegap/PNPAA-Ionic/mobile/platforms/android/build/outputs/apk/android-x86-release-unsigned.apk
    /home/adones/Projects/Phonegap/PNPAA-Ionic/mobile/platforms/android/build/outputs/apk/android-armv7-release-unsigned.apk

```

instead of just `android-release.apk`.

Here's my gulp task:

```

var gulp = require('gulp');
var android = require('gulp-cordova-build-android');
var del = require('del');

gulp.task('release:android', ['build:assets','compress', 'host'], function(done) {

    del('releases/android/*', function () {

      gulp.src('../')
      .pipe(android({
        storeFile: '/home/adones/Projects/Phonegap/PNPAA-Ionic/mobile/pnpaa-release.keystore',
        keyAlias: 'alias_name'      
      }))
      .pipe(gulp.dest('releases/android/'))
      .on('end', done);

    });
});
```

After the task has finished, the `releases/android/` directory is still empty.

**Comment by SamVerschueren** [comment]
Hi @adonespitogo 

Glad you like it :).

Is this a new android thing or is it specific for using crosswalk or ionic? If you don't know for sure I guess I have to find out. But any help is welcome.

**Comment by adonespitogo** [comment]
I don't know if this is specific to crosswalk/ionic. There might be other tools that could modify the release apk names so this problem will surely occur if ever.

**Comment by bennybennet** [comment]
Same here. Since I've added the crosswalk plugin to my project i'm getting:

```
Built the following apk(s):
    .../.cordova/platforms/android/build/outputs/apk/android-x86-debug.apk
    .../.cordova/platforms/android/build/outputs/apk/android-armv7-debug.apk
[16:04:15] Plumber found unhandled error:
 Error in plugin 'gulp-cordova-build-android'
Message:
    ENOENT, no such file or directory '.../.cordova/platforms/android/build/outputs/apk/android-debug.apk'
```

**Comment by SamVerschueren** [comment]
There was a PR on this but am not quite into the solution provided. Instead of just returning the `android-release.apk` file, I will return the all the .apk files in `platforms/android/build/outputs/apk`. This provides more flexibility because then the 'user' of the library can pick the apk he wants and we don't have this issue anymore because the name isn't hardcoded anymore. What do you think?

**Comment by SamVerschueren** [comment]
Added this in `v1.3.0`. When piping the result to `gulp.dest('apks')`, all the apk files in the outputs/apk directory will be stored in the `apks` directory.
