### ISSUE TITLE
android platform target version?

### ISSUE THREAD

**Issue by ghost** [SamVerschueren/gulp-cordova-build-android#6]
Can't seem to figure out how to change the api version the apk is build against.

**Comment by SamVerschueren** [comment]
I found on StackOverflow that it should be possible with setting the preference. http://stackoverflow.com/questions/18384723/how-do-i-specify-the-android-api-level-in-phonegap

Can you give it a try and let me know if it works?

``` xml
<preference name="android-targetSdkVersion" value="14" />
<preference name="android-minSdkVersion" value="14" />
```

Use [gulp-cordova-preference](https://github.com/SamVerschueren/gulp-cordova-preference) to set the values.

**Comment by ghost** [comment]
Tried that doesn't work. Still using 22.

**Comment by ghost** [comment]
@SamVerschueren maybe config.xml is being read for the build process before preferences writes to it?

**Comment by ghost** [comment]
``` javascript
function buildCordova(debug /*boolean*/, done /* callback */) {
    var cordova = {
        create: plugins.cordovaCreate,
        plugin: plugins.cordovaPlugin,
        android: plugins.cordovaBuildAndroid,
        cmd: plugins.cordova,
        version: plugins.cordovaVersion,
        preference: plugins.cordovaPreference,
        description: plugins.cordovaDescription,
        author: plugins.cordovaAuthor
    };

    var apkOptions;
    if (!debug) {
        apkOptions = {
            release: true,
            storeFile: '.....'
            keyAlias: 'alias_name'
        };
    }

    var version;
    if (!debug) {
        version = incrementPatchVersion();
        announce('VERSION CHANGED!', version);
    }
    else {
        version = getVersion(getManifest())
        announce('VERSION', version);
    }

    gulp.src(config.path.dist)
        .pipe(cordova.create({
            id: config.appId,
            name: config.moduleName.toLowerCase()
        }))
        .pipe(cordova.version(version))
        .pipe(cordova.preference({
            'android-minSdkVersion': '17',
            'android-targetSdkVersion': '17',
            'loadUrlTimeoutValue': '30000'
         }))
        .pipe(cordova.plugin('org.apache.cordova.dialogs'))
        .pipe(cordova.plugin('https://github.com/rodenis/reader-plugin.git'))
        .pipe(cordova.plugin('https://github.com/katzer/cordova-plugin-printer.git'))
        .pipe(cordova.plugin('https://github.com/pankajnirwan103/cordova-plugin-printer.git'))
        .pipe(cordova.android(apkOptions))
        .pipe(gulp.dest('../' + config.path.cordovaOutput))
        .on('end', done);
}
```

**Comment by SamVerschueren** [comment]
I tried to find how you can do this but without success. It adds the `<uses-sdk />` tag to AndroidManifest.xml so that's a good thing. But it always picks the highest sdk available. Although I'm not sure this is a bug. I'm not really an Android expert at all, but the `minSdkVersion` says that devices running a lower version then 17, are not able to install the application. The `targetSdkVersion` tells the compiler that the application is designed for that API level. I don't think it has anything to do with the version of the compiler the applications compiles with.

Any thoughts and/or ideas are welcome :).

**Comment by ghost** [comment]
I tried putting the apk on a 4.3.0 device and it had an apk error, wouldn't install.

@SamVerschueren  Looks like you need to modify project.properties in platforms/android/project.properties

http://stackoverflow.com/a/30206467/263457

Perhaps another plugin is needed to set the config.xml and the project.properties.target.

edit:

```
# This file is automatically generated by Android Tools.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
```

tried manually modifying the properties file in my .cordova folder in my project and in my user folder. Android Tools seems to override both :(

**Comment by SamVerschueren** [comment]
Thanks for the information. Will have a deeper look at it. If you find more information regarding this topic, please share with me.

**Comment by SamVerschueren** [comment]
@robertbaker Is this resolved?

**Comment by ghost** [comment]
Yes by specifying the min and target sdk, it builds a compat apk. Turns out
a plugin was causing the invalid apk error.

**Comment by SamVerschueren** [comment]
Hopefully it wasn't one of my plugins :). Thanks for the feedback.
